Add jenkins client communicated with the Jenkins API
jubaky/api_server pull request #1
Opened 2019-07-30 13:15 UTC by ByeongGil-Jung

Add jenkins client communicated with the Jenkins API

- initJenkinsClient
:: Init the JenkinsClient object with several environments
- redirectGithubWebhook
:: Redirect github webhook connection to Jenkins webhook
- getJobInfo
:: Get the info of the jenkins job
- getJobSpecInfo
:: Get the specific information of the jenkins job on build number
- getJobLog
:: Get the job log on build number
- createJob
:: Create the jenkins job
- deleteJob
:: Delete the jenkins job
- updateJob
:: Modify the jenkins job
- buildWithParameters
:: Build the jenkins job with several parameters
- createCredentials
:: Create jenkins credentials to connect the github account
- deleteCredentials
:: Delete jenkins credentials

(19.07.30)

2019-07-30 13:53 UTC, jdekim43 requested changes

2019-07-30 13:53 UTC, jdekim43 commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
필드가 전부 nullable 인데 nonnull 로는 할 수 없는거야?

2019-07-30 13:53 UTC, jdekim43 commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobInfo.kt
> +    var description: String? = null
constructor 로 안하고 일반 인스턴스 변수로 뺀 이유가 뭐야?

2019-07-30 13:53 UTC, jdekim43 commented on domain/src/main/kotlin/org/jaram/jubaky/service/JenkinsService.kt
> +    suspend fun redirectGithubWebhook(headers: Map<String, String>, payload: String): String? {
github 에 의존되는 webhook 보다는 git 에서 지원하는 hook 이나 외부에서 직접 호출 가능한 엔드포인트를 노출하는건 어때?

2019-07-30 13:53 UTC, jdekim43 commented on domain/src/main/kotlin/org/jaram/jubaky/service/JenkinsService.kt
> +        return jenkinsRepository.getJobInfo(jobName!!)
nullable 로 들어온 파라미터는 그냥 바로 사용하는건 좀 위험한듯

애초에 non null 로 받던가 별도의 예외처리가 필요해보여

2019-07-30 13:53 UTC, jdekim43 commented on jenkins/build.gradle.kts
> +    implementation("com.squareup.retrofit2:converter-scalars:2.6.0")
scalar converter 는 어디에서 사용되는거야?

2019-07-30 13:53 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/JenkinsClient.kt
> +        @Query("token") token: String,
이 코드 확인이 필요할 것 같은데

Query 로 하면 query parameter 로 추가되는데 post 는 일반적으로 body 에 payload 를 실어 보내는거라서
Field 로 바꾸고 @FormUrlEncoded 어노테이션 추가하는게 어때?

2019-07-30 13:53 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/JenkinsClientFactory.kt
> +    lateinit var username: String
이 오프젝트만 놓고 봤을 때 username 을 설정하기 전에 다른 메소드를 호출할 수 있어서 오류 가능성이 있을 것 같아

class 로 바꾸고 이런 필요한 값들은 생성자로 받는게 어때?

2019-07-30 13:53 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/JenkinsClientFactory.kt
> +        val retrofit = Retrofit.Builder()
retrofit 을 만드는게 메소드 안에 있어서 client 만들 때마다 retrofit 을 생성하게 되서 불필요한 리소스가 소모될 것 같은데 retrofit builder 는 밖으로 빼는게 어때?

2019-07-30 13:53 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/JenkinsClientFactory.kt
> +        this.jenkinsClientDefault = createJenkinsClientDefault(baseUrl)
같은 인터페이스를 각각 다른 retrofit client 를 사용하고 있는데
이렇게 하면 인터페이스 안에서 사용할 수 있는 메소드와 사용할 수 없는 메소드가 구분되지 않을까?

retrofit client 별로 인터페이스를 구분하는게 좋을 것 같아

2019-07-30 13:53 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +    override fun initJenkinsClient(baseUrl: String, username: String, token: String) {
jenkins client 는 koin 을 통해서 주입받는건 어때?

2019-07-30 13:53 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +        val request = JenkinsClientFactory.jenkinsClientWithJson.redirectGithubWebhook(headers, requestBody)
인터페이스를 분리하고 해당 인터페이스를 생성자로 주입받으면 코드가 조금 더 간결해질 것 같고 개발자가 api 를 사용하기 위해 알아야할 게 줄어서 개발할 때 조금 더 편해질 것 같아

2019-07-30 13:53 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +            val data = response.body()
jackson converter 를 사용하고 있으니까 응답을 data class 로 만들어 사용하는건 어때?

2019-07-30 13:53 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +            resultLog = response.body()!!
nullable 에 대해서는 바로 nonnull 로 처리하기보다는 ? 를 활용해서 예외처리를 해주는게 좋을 것 같아

2019-07-30 13:53 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +        return resultValue
resultValue 가  success 만 있는거라면 Boolean 으로 처리하는건 어때?
다른 정보가 있는거라면 enum 으로 처리하거나 별도의 코드와 메시지가 담긴 class 를 만드는 것도 좋을 것 같아

그리고 그냥 애초에 그냥 예외를 던져도 좋을 것 같아

2019-07-30 13:53 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +        val credData: String =
코틀린에는 문자열 여러줄로 만들 수 있으니까 그걸로 바꾸는게 좋을 것 같고
변수와 조합되고 이런 경우라면 jackson 으로 json 을 만들거나 클래스를 만들어서 jackson 으로 변환하는게 좋을 것 같아

2019-07-30 13:53 UTC, jdekim43 commented on presenter/src/main/kotlin/org/jaram/jubaky/presenter/JubakyServer.kt
> +    val jenkinsProtocol = properties.getString("jenkins.protocol") ?: ""
koin 으로 property 도 주입받을 수 있으니까 그걸로 바꾸는게 좋을 것 같아
모든 설정을 여기에 다 추가할 수는 없으니까

2019-07-30 13:53 UTC, jdekim43 commented on presenter/src/main/kotlin/org/jaram/jubaky/presenter/router/DevRouter.kt
> +            val postParameters = call.receiveParameters()
파라미터 처리에 대해서 function 만들어놨으니까 그거 사용하는게 좋을듯
queryParam
bodyParam
pathParam

2019-07-30 13:53 UTC, jdekim43 commented on presenter/src/main/kotlin/org/jaram/jubaky/presenter/router/DevRouter.kt
> +        post("/specInfo") {
url path 에는 undercase 사용하는게 어때?

2019-07-30 13:53 UTC, jdekim43 commented on presenter/src/main/kotlin/org/jaram/jubaky/presenter/router/DevRouter.kt
> +        post("/create") {
이미 post 가 create 의 의미를 가지고 있어서 그냥 / 로 해도 좋을 것 같아

2019-07-30 13:53 UTC, jdekim43 commented on presenter/src/main/kotlin/org/jaram/jubaky/presenter/router/DevRouter.kt
> +        post("/delete") {
restful 하게 delete 로 바꾸고 body payload 대신에 path parameter 로 바꾸는게 어때?

2019-07-30 13:53 UTC, jdekim43 commented on presenter/src/main/kotlin/org/jaram/jubaky/presenter/router/DevRouter.kt
> +private fun buildResponseMap(data: Any?): Map<String, Any?> {
이거 대신에 BaseResponse 만들어 놓은거 있는데 그거 쓰는게 어때?

2019-07-31 09:35 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
처음에 그렇게 했는데 받아오는 값이 아예 없는 경우가 많아서 그랬음
그러면 null 일 경우에 default value로 String 이면 ""이고 Int 이면 -1 로 주면 될까

2019-07-31 09:35 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobInfo.kt
> +    var description: String? = null
오키 이거는 처음 dto 만들 때 data class 헷갈려서 이렇게 만들었는데 수정하겠음

2019-07-31 09:35 UTC, ByeongGil-Jung commented on jenkins/build.gradle.kts
> +    implementation("com.squareup.retrofit2:converter-scalars:2.6.0")
이거는 Log 받아올 때 text만으로 받아왔나 그랬는데 따로 scalar converter 를 해줘야 한대서 넣었음

2019-07-31 09:35 UTC, ByeongGil-Jung commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/JenkinsClient.kt
> +        @Query("token") token: String,
이거는 jenkins API가 이렇게 받아서 어쩔 수 없는 거 같아

2019-07-31 09:36 UTC, ByeongGil-Jung commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/JenkinsClientFactory.kt
> +    lateinit var username: String
singleton 이 아니면 좀 비효율적인 거 같아서 object로 만들었음

그래서 처음에 서버 실행할 때 db에서 값을 받아오면서 생성하게끔 하구, 운용 중에 값이 변경될 수도 있으니까 init 함수를 만들어놨는데 그럼 괜찮지 않을까

2019-07-31 09:36 UTC, ByeongGil-Jung commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/JenkinsClientFactory.kt
> +        val retrofit = Retrofit.Builder()
이게 api 마다 사용하는 converter도 다르고 intercept의 유무도 달라서 필요한 client를 미리 만들어 놓는게 좋겠다고 생각했어. 한 인스턴스에 저장해 놓으니까 여러 번 생성할 필요두 없을거구

2019-07-31 09:36 UTC, ByeongGil-Jung commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/JenkinsClientFactory.kt
> +        this.jenkinsClientDefault = createJenkinsClientDefault(baseUrl)
오키 분리하겠음

2019-07-31 09:36 UTC, ByeongGil-Jung commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +    override fun initJenkinsClient(baseUrl: String, username: String, token: String) {
이거는 혹시 운용 중에 token같은 값들이 바뀔 수도 있을 거 같아서 init 함수를 만들어놨음

맨 처음에 주입하도록 하는건 그렇게 할게

2019-07-31 09:36 UTC, ByeongGil-Jung commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +            val data = response.body()
처음에 그렇게 했었는데 생각보다 nested 된 게 많았고 응답의 json 구조가 생각보다 유동적으로 바뀌어서 파싱하는게 좋을 거 같았어

2019-07-31 09:36 UTC, ByeongGil-Jung commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +            resultLog = response.body()!!
오키 수정하겠음

2019-07-31 09:36 UTC, ByeongGil-Jung commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +        return resultValue
아 나도 그게 좋을 거 같다고 생각하긴 했는데 수정할게

2019-07-31 09:36 UTC, ByeongGil-Jung commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +        val credData: String =
오키

2019-07-31 09:36 UTC, ByeongGil-Jung commented on presenter/src/main/kotlin/org/jaram/jubaky/presenter/JubakyServer.kt
> +    val jenkinsProtocol = properties.getString("jenkins.protocol") ?: ""
이거는 koin에 아직 익숙하질 않아서 일단 이렇게 했는데 좀 더 알아보구 수정하겠음

2019-07-31 09:36 UTC, ByeongGil-Jung commented on presenter/src/main/kotlin/org/jaram/jubaky/presenter/router/DevRouter.kt
> +            val postParameters = call.receiveParameters()
옹키 저 만든것들 봤는데 어디에 어떻게 사용하는지 감이 잘 안왔었음

2019-07-31 09:36 UTC, ByeongGil-Jung commented on presenter/src/main/kotlin/org/jaram/jubaky/presenter/router/DevRouter.kt
> +        post("/specInfo") {
오키도키 수정하겠음

2019-07-31 09:36 UTC, ByeongGil-Jung commented on presenter/src/main/kotlin/org/jaram/jubaky/presenter/router/DevRouter.kt
> +        post("/create") {
넹

2019-07-31 09:36 UTC, ByeongGil-Jung commented on presenter/src/main/kotlin/org/jaram/jubaky/presenter/router/DevRouter.kt
> +        post("/delete") {
넵

2019-07-31 09:37 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/service/JenkinsService.kt
> +        return jenkinsRepository.getJobInfo(jobName!!)
오키 위랑 같이 수정할게

2019-07-31 09:46 UTC, ByeongGil-Jung commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/repository/JenkinsRepositoryImpl.kt
> +    override fun initJenkinsClient(baseUrl: String, username: String, token: String) {
init 함수는 운용 중에 token같은 값들이 바뀔 수도 있을 거 같아서 만들어놨어

koin  주입은
내가 아직 koin 감이 잘 안잡혔는데 Main.kt 에서 주입시키면 되는거야 ?

2019-07-31 09:50 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobInfo.kt
> +    var description: String? = null
아 이거는 처음 dto 만들 때 data class 헷갈려서 이렇게 만들었는데 수정하겠음

2019-07-31 09:51 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobInfo.kt
> +    var description: String? = null
오키 이거는 처음 kotlin dto 만질 때 data class 헷갈려서 이렇게 만들었는데 수정하겠음

2019-07-31 09:51 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobInfo.kt
> +    var description: String? = null
이거는 처음 kotlin dto 만질 때 data class 헷갈려서 이렇게 만들었는데 수정하겠음

2019-07-31 10:35 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
아 그리고 혹시 data class에서 null 로 받을 때 default value를 주게 하는 방법이 없나
구글링 해도 명확한 답을 잘 못보겠네
줄 때마다 값을 핸들링 해줘야 하나

2019-07-31 10:48 UTC, jdekim43 requested changes

2019-07-31 10:48 UTC, jdekim43 commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
없는걸 굳이 넣을 필요는 없는데 jobName 도 없는 경우가 있어?
만약 이 클래스를 공유해야해서 nullable 로 할 수 밖에 없는거면 클래스를 쪼개는게 맞을 것 같아
buildArgumentList 같은건 emptyList 를 줘도 괜찮을듯

2019-07-31 10:48 UTC, jdekim43 commented on jenkins/build.gradle.kts
> +    implementation("com.squareup.retrofit2:converter-scalars:2.6.0")
plain text 면 그냥 아무 converter 안넣어도 되지 않아?

2019-07-31 10:48 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/JenkinsClientFactory.kt
> +    lateinit var username: String
koin 을 활용하면 singleton 으로 유지할 수 있어
유틸을 제외하고는 class 로 하는게 좋을 것 같아

2019-07-31 10:48 UTC, jdekim43 commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/JenkinsClientFactory.kt
> +        val retrofit = Retrofit.Builder()
만들어진 client 를 koin 에 저장해서 koin 에서 주입받으면 될 것 같아

2019-07-31 10:48 UTC, jdekim43 commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
그거는 자바도 없지 않나?
그리고 jenkins api 의 응답에 대해서는 response model 을 따로 만드는게 맞을 것 같아
이거는 도메인 모델이라서

2019-07-31 11:49 UTC, ByeongGil-Jung commented on jenkins/build.gradle.kts
> +    implementation("com.squareup.retrofit2:converter-scalars:2.6.0")
처음에 안넣고 했는데 인식을 못하더라구 ㅠㅠ 그래서 찾아봤더니 scalar converter 를 적용시켜야 한대

2019-07-31 11:50 UTC, ByeongGil-Jung commented on jenkins/src/main/kotlin/org/jaram/jubaky/jenkins/JenkinsClientFactory.kt
> +    lateinit var username: String
오키 ~~

2019-07-31 11:56 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
아 미안미안 클래스를 헷갈렸음
저거 JobConfig는 job 만들거나 수정할 때 프론트에서 받아온 값을 쓰는 거라서 굳이 nullable로 안해도 될 거 같아
혹시 값이 없는 경우가 있을까봐 nullable을 넣어놨던 거였어

2019-07-31 11:57 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
jenkins api 응답이 null 인 경우가 많은데 괜찮아 ?

2019-08-01 01:07 UTC, jdekim43 requested changes

2019-08-01 01:07 UTC, jdekim43 commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
정책을 정하면 될 것 같은데 nullable 로 할지 기본값으로 할지

2019-08-05 11:06 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
jenkis api 응답에 관한 data class 들을 jenkins 모듈에 넣으려고 했는데
Repository, Service 등에서도 이걸 사용하는데 import가 안되네

이거를 공유하게끔 할 수 있는 좋은 방법이 없을까 ?
모듈에서 주입을 해야할까 ?

2019-08-06 01:36 UTC, jdekim43 commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
그 data class 들을 domain 에서 사용하면 안되서 jenkins 모듈에 넣는거야
jenkins 응답 형식에 의존이 생기기 때문에 response 모델과 domain model 을 분리하는거지
그래서 RepositoryImpl 이나 DataSource 쪽에서 response model -> domain model 로 변환해주는 작업을 해줘야해

2019-08-06 07:51 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
옹키
근데 계속 생각했는데
내가 이것들을 response 결과들을 바로 전부 매핑한게 아니라 필요한 정보들만 선별해서 매핑한거라이걸 domain model에 넣어도 되지 않을까

kubernetes에도 Pod domain model이 있는거처럼.
사실 이것도 JobInfo라고 했지만 Job이랑 똑같은거거든

2019-08-06 07:52 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
옹키
근데 계속 생각했는데
내가 이것들을 response 결과들을 바로 전부 매핑한게 아니라 필요한 정보들만 선별해서 매핑한거라이걸 domain model에 넣어도 되지 않을까

kubernetes에도 Pod domain model이 있는거처럼.
이름을 JobInfo라고 했지만 Job이랑 똑같은 의미거든

2019-08-06 07:53 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
이 data class 그대로 jubaky response 로 뿌릴려고 했었거든

2019-08-06 07:56 UTC, jdekim43 commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
일단 나중에 응답값이 뭐가 있었는지 헷갈리지 않기 위해서는 응답값에 대해서는 전부 class 에 추가해놓는게 좋다고 생각하고
만약 두개가 정확히 일치한다면 편의를 위해 domain 모델 그대로를 사용해도 된다고 생각해
다만 response model 에서는 nullable 인 값이 domain model 에서는 nonnull 인 경우라면 분리해주는게 좋다고 생각해

2019-08-06 10:41 UTC, ByeongGil-Jung commented on domain/src/main/kotlin/org/jaram/jubaky/domain/JobConfig.kt
> +data class JobConfig(
오키도키 ~

2019-08-07 12:55 UTC, closed without merging